name: Build
on: push
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: bilby91/ddns-cloudflare
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -x -s -- -y
    - name: Install Cross
      run: cargo install cross
    - name: Compile source
      run: cross build --target x86_64-unknown-linux-musl --release
    - name: Build docker image
      run: |
        docker build \
          -f docker/Dockerfile.x86_64 \
          -t "$CI_REGISTRY_IMAGE:x86_64-$GITHUB_SHA" .
    - name: Push pull request image tag
      run: docker push "$CI_REGISTRY_IMAGE:x86_64-$GITHUB_SHA"

  build-armv7:
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY_IMAGE: bilby91/ddns-cloudflare
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Install Rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -x -s -- -y
    - name: Install Cross
      run: cargo install cross
    - name: Compile source
      run: cross build --target armv7-unknown-linux-musleabihf --release
    - name: Build docker image
      run: |
        docker buildx build \
          --platform=linux/arm/v7 \
          --push \
          -f docker/Dockerfile.armv7 \
          -t "$CI_REGISTRY_IMAGE:armv7-$GITHUB_SHA" .